import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import Footer from "@/components/footer";
import { CartProvider } from "@/contexts/cart-context";
import { cookies } from "next/headers";
import { getCart } from "@/lib/shopify";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Coding Jitsu Store",
  description: "Generated by create next app",
};

interface Props {
  children: React.ReactNode;
}

const RootLayout: React.FC<Props> = async ({
  children,
}) => {
  const cookiesStore = await cookies()
  const cartId = cookiesStore.get("cartId")?.value;
  const cart = await getCart(cartId);
  console.log({ cart })
  return (
    <html lang="en">
      <body className={inter.className}>
        <CartProvider cart={cart}>
          <Navbar />
          {children}
          <Footer />
        </CartProvider>
      </body>
    </html>
  );
}

export default RootLayout
